cluster-version: v5.1.0
patch: tikv-server.tar.gz
cluster-name: iosmanthus-backup
old-topology: config/old.yaml
new-topology: config/new.yaml
join-topology: config/join.yaml
recover-info-file: bin/recover-info.json
zone-labels:
  - zone: az4
  - zone: az5
tikv-ctl:
  src: bin/tikv-ctl
  dest: /root/tikv-ctl
pd-recover-path: bin/pd-recover
pd-ctl-commands:
  - store limit all 500 add-peer
new-placement-rules: config/step0.json # placement rules for new cluster
extra-ssh-opts: -i config/id_rsa

