name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.16.7"
      - name: "Build"
        run: |
          make
          tar -cvzf learner-recover.tar.gz learner-recover rpo.sh recover.sh fetcher.sh config

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release Build"
          files: |
            learner-recover.tar.gz
            sha256sum
